#!/bin/sh
#
#  Call ruby script to check if test settings (simp_conf.yaml generated
#  for the test) match the system settings and, in for some checks, the
#  hieradata generated by 'simp config' (simp_config_settings.yaml).
#

set -e

ERR_NO_RUBY_EXE=71

for pth in /opt/puppetlabs/puppet/bin /opt/puppetlabs/bin; do
  if [ -z "$RUBY" ] && [ -x "$pth/ruby" ]; then
    export PATH="$pth:${PATH}"
    RUBY="$pth/ruby"
  fi
done
[ -z "$RUBY" ]&& { echo "ERROR: could not find a ruby executable"; exit "${ERR_NO_RUBY_EXE}"; }

pupenv=$(puppet config print environment 2> /dev/null)
packerdir=${VAR_LOCAL_SIMP_DIR:-"/var/local/simp"}
pupenvdir="$(puppet config print environmentpath 2> /dev/null)"
hieradata_dir="${pupenvdir}/${pupenv}/data"

simp_default="${hieradata_dir}/simp_config_settings.yaml"

SIMP_PACKER_environment=$pupenv ruby "${packerdir}/scripts/tests/check_settings.rb" "${packerdir}/files/simp_conf.yaml" "${simp_default}"
