#!/usr/bin/sh
#
#  Call ruby script to check if test settings (simp_conf.yaml generated
#  for the test) match the system settings and, in for some checks, the
#  hieradata generated by 'simp config' (simp_config_settings.yaml).
#

set -e

export PATH="${PATH}:/opt/puppetlabs/bin"
packerdir="/var/local/simp"
pupenvdir=$(puppet config print environmentpath)
simp_default="${pupenvdir}/simp/hieradata/simp_config_settings.yaml"

"${packerdir}/scripts/tests/check_settings.rb" "${packerdir}/files/simp_conf.yaml" "${simp_default}"


