fixtures:
    symlinks:
      simpsetup: "#{source_dir}"
    repositories:
      concat: https://github.com/simp/puppetlabs-concat.git
      simplib: https://github.com/simp/pupmod-simp-simplib.git
      stdlib: https://github.com/simp/puppetlabs-stdlib.git
