# @summary Creates LDAP users and groups.
#
# This class creates scripts and, as appropriate LDIF files, and then uses them
# to add/modify LDAP users and groups.
#
# @param env
#   The Puppet environment
#
# @param ldap_base_dir
#   The base location for LDAP setup interim artifacts
#
# @param ldap_dir
#   The location for LDAP setup interim artifacts for $env
#
# @param base_dn
#   The LDAP Base DN
#
# @param relver
#   The OS major release version of the server on which the LDAP server resides
#
#   * When '7', the LDAP server is assumed to be an OpenLDAP server
#   * Otherwise, the LDAP server is assumed to be a 389-DS server
#
# @param groups
#   Hash of group name to gidNumber
#
#   * Any other required LDAP attributes required to create a posixgroup for
#     each group will be autogenerated
#
# @param users
#   Hash of user name to user info Hash
#
#   * Info Hash contains uidNumber, gidNumber, and sec_groups
#   * sec_groups is an Array of secondary group names the user belongs to
#   * Any other required LDAP attributes required to create the user will be
#     autogenerated
#
class simpsetup::ldap(
  String                      $env           = $simpsetup::environment,
  String                      $ldap_base_dir = '/root/ldap',
  String                      $ldap_dir      = "${ldap_base_dir}/${env}",
  String                      $base_dn       = simplib::ldap::domain_to_dn($simpsetup::domain, true),
  String                      $relver        = $simpsetup::relver,
  Hash[String,Integer]        $groups        = {
    'admin1'     => 3001, # primary group of admin1 user
    'admin2'     => 3002, # primary group of admin2 user
    'auditor1'   => 7001, # primary group of auditor1 user
    'baduser'    => 9001, # primary group of baduser user
    'NotAllowed' => 9999,
    'user1'      => 4001, # primary group of user1 user
    'user2'      => 4002, # primary group of user2 user
    'testgroup'  => 4000,
    'security'   => 7700  # SIMP's auditor group (simp::admin::auditor_group).
                          # Allowed ssh access for historical reasons, but not
                          # created in LDAP by default.
  },
  Hash[String,Simpsetup::LdapUser] $users         = {
    # - By default, SIMP allows ssh access to users in the 'administrators' and
    #   'security' groups via simp::admin
    # - 'administrators' and 'users' group are already created by default in LDAP
    'admin1'   => { 'uidNumber' => 3001, 'gidNumber' => 3001, 'sec_groups' => [ 'users', 'administrators'] },
    'admin2'   => { 'uidNumber' => 3002, 'gidNumber' => 3002, 'sec_groups' => [ 'users', 'administrators'] },
    'auditor1' => { 'uidNumber' => 7001, 'gidNumber' => 7001, 'sec_groups' => [ 'security'] },
    'baduser'  => { 'uidNumber' => 9001, 'gidNumber' => 9001, 'sec_groups' => [ 'NotAllowed'] },
    'user1'    => { 'uidNumber' => 4001, 'gidNumber' => 4001, 'sec_groups' => [ 'testgroup', 'users'] },
    'user2'    => { 'uidNumber' => 4002, 'gidNumber' => 4002, 'sec_groups' => [ 'testgroup', 'users'] }
  }
) {

  assert_private()

  file { $ldap_base_dir:
    ensure  => 'directory',
    owner   => 'root',
    group   => 'root',
    mode    => '0750',
  }

  file { $ldap_dir:
    ensure  => 'directory',
    owner   => 'root',
    group   => 'root',
    mode    => '0750',
  }

  if $relver == '7' {
    include 'simpsetup::ldap::openldap'
  }
  else {
    include 'simpsetup::ldap::ds389'
  }
}
