# @summary Creates LDAP users and groups on a SIMP's 389-DS 'accounts' instance
#
# This class creates a script then uses it to add/modify LDAP users and groups.

# @param $ldap_dir
#   Base location of script generated by this class
#
# @param $base_dn
#   The LDAP Base DN
#
# @param groups
#   Hash of group name to gidNumber
#
#   * Any other required LDAP attributes required to create a posixgroup for
#     each group will be autogenerated
#
# @param users
#   Hash of user name to user info Hash
#
#   * Info Hash contains uidNumber, gidNumber, and sec_groups
#   * sec_groups is an Array of secondary group names the user belongs to
#   * Any other required LDAP attributes required to create the user will be
#     autogenerated
#
# @param $user_password_hash
#   The encrypted password used to set the initial password for all users
#   - IMPORTANT: 389-DS will force the users to change that password upon first
#     login. This is different behavior than that of the OpenLDAP server.
#     See simp-core's LDAP acceptance tests for expect scripts that can be
#     used to change passwords in a test.

class simpsetup::ldap::ds389(
  String                           $ldap_dir           = $simpsetup::ldap::ldap_dir,
  String                           $base_dn            = $simpsetup::ldap::base_dn,
  Hash[String,Integer]             $groups             = $simpsetup::ldap::groups,
  Hash[String,Simpsetup::LdapUser] $users              = $simpsetup::ldap::users,
  # encrypted user password generated on a server with a 389-DS accounts instance:
  #   pwdhash -D /etc/dirsrv/slapd-accounts 'P@ssw0rdP@ssw0rd'
  String                           $user_password_hash = "{SSHA512}37RfyKG546rvNfAuGB3yiKeFYQTwXlA/cPVKS6eeMQPNcqHoDL962i2UbavsMWHADIW4ejWidkEh1ADmWY9KcajxZk2Njxf2"
) {
  assert_private()

  $_add_users_script =  "${ldap_dir}/add_users_389ds.sh"
  file { $_add_users_script:
    owner   => 'root',
    group   => 'root',
    mode    => '0750',
    content =>  template('simpsetup/ldap/scripts/add_test_users_389ds.sh.erb')
  }

  exec { 'packer_add_users_to_389ds':
    command => $_add_users_script,
    cwd     => $ldap_dir,
    require => File[$_add_users_script]
  }
}
